# Generated by Django 3.1.7 on 2021-03-17 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(default='Action Item 2021-03-17 21:38:02', max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('story_points', models.IntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('scoped', 'Scoped'), ('in progress', 'In Progress'), ('blocked', 'Blocked'), ('validating', 'Validating'), ('complete', 'Complete')], max_length=50, verbose_name='Status')),
                ('completion_date_proj', models.DateField(blank=True, null=True, verbose_name='Projected Completion Date')),
                ('completion_date_actual', models.DateField(blank=True, null=True, verbose_name='Actual Completion Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('is_self', models.BooleanField(default=False, verbose_name='Self?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('impact', models.TextField(verbose_name='Impact')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scoping', 'Scoping'), ('in progress', 'In Progress'), ('complete', 'Complete')], max_length=50, verbose_name='Status')),
                ('completion_date_proj', models.DateField(blank=True, null=True, verbose_name='Projected Completion Date')),
                ('completion_date_actual', models.DateField(blank=True, null=True, verbose_name='Actual Completion Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('requirement', 'Requirement'), ('nice to have', 'Nice to Have'), ('blocker', 'Blocker')], max_length=100, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tas_from_action_item', to='app.actionitem')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tas_to_project', to='app.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('user', 'User'), ('governance', 'Governance'), ('influencer', 'Influencer'), ('provider', 'Provider')], max_length=100, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_poc', models.BooleanField(default=False, verbose_name='Point of Contact?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sta_from_person', to='app.person')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sta_to_project', to='app.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_person', to='app.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_person', to='app.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(default='Note 2021-03-17 21:38:02', max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(default='Meeting 2021-03-17 21:38:02', max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(default='Attachment 2021-03-17 21:38:02', max_length=100, verbose_name='Title')),
                ('file', models.FileField(upload_to='', verbose_name='Attachment')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('notes', 'Note'), ('minutes', 'Minutes'), ('scoping', 'Scoping')], max_length=20, verbose_name='Type')),
                ('origin', models.BooleanField(default=True, verbose_name='Origin?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_from_note', to='app.note')),
                ('to_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_to_meeting', to='app.meeting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('scoping', 'Scoping'), ('update', 'Update'), ('presentation', 'Presentation'), ('debrief', 'Debrief')], max_length=100, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis_from_meeting', to='app.meeting')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis_to_project', to='app.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('leader', 'Leader'), ('team member', 'Team Member'), ('contributor', 'Contributor')], max_length=100, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_poc', models.BooleanField(default=False, verbose_name='Point of Contact?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_from_person', to='app.person')),
                ('to_action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_to_action_item', to='app.actionitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_from_person', to='app.person')),
                ('to_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_to_meeting', to='app.meeting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
