# Generated by Django 3.1.7 on 2021-03-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date_actual',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date_proj',
            field=models.DateField(blank=True, null=True, verbose_name='Projected Start Date'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='title',
            field=models.CharField(default='Action Item 2021-03-18 05:48:13', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='Attachment 2021-03-18 05:48:13', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting 2021-03-18 05:48:13', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note 2021-03-18 05:48:13', max_length=100, verbose_name='Title'),
        ),
    ]
