# Generated by Django 3.1.7 on 2021-03-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210318_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='title',
            field=models.CharField(default='Action Item 2021-03-18 05:51:57', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='Attachment 2021-03-18 05:51:57', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting 2021-03-18 05:51:57', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note 2021-03-18 05:51:57', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
