# Generated by Django 3.1.7 on 2021-03-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210318_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='title',
            field=models.CharField(default='Action Item 2021-03-19 00:51:10', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='Attachment 2021-03-19 00:51:10', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting 2021-03-19 00:51:10', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note 2021-03-19 00:51:10', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project 2021-03-19 00:51:10', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='type',
            field=models.CharField(choices=[('user', 'User'), ('governance', 'Governance'), ('influencer', 'Influencer'), ('provider', 'Provider'), ('participant', 'Participant')], max_length=100, verbose_name='Type'),
        ),
    ]
