# Generated by Django 3.1.7 on 2021-03-19 18:19

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210319_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='description',
            field=djrichtextfield.models.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='title',
            field=models.CharField(default='Action Item 2021-03-19 18:19:30', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='Attachment 2021-03-19 18:19:30', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=djrichtextfield.models.RichTextField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting 2021-03-19 18:19:30', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=djrichtextfield.models.RichTextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note 2021-03-19 18:19:30', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=djrichtextfield.models.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='impact',
            field=djrichtextfield.models.RichTextField(verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project 2021-03-19 18:19:30', max_length=100, verbose_name='Title'),
        ),
    ]
