# Generated by Django 3.1.7 on 2021-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210319_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='status',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('scoped', 'Scoped'), ('in progress', 'In Progress'), ('blocked', 'Blocked'), ('validating', 'Validating'), ('complete', 'Complete')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='story_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='title',
            field=models.CharField(default='Action Item 2021-03-19 19:32:00', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='Attachment 2021-03-19 19:32:00', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting 2021-03-19 19:32:00', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note 2021-03-19 19:32:00', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project 2021-03-19 19:32:00', max_length=100, verbose_name='Title'),
        ),
    ]
