# Generated by Django 3.1.7 on 2021-03-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210319_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Queued', 'queued'), ('Scoped', 'scoped'), ('In Progress', 'in progress'), ('Blocked', 'blocked'), ('Validating', 'validating'), ('Complete', 'complete')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='title',
            field=models.CharField(default='Action Item 2021-03-19 20:39:09', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='type',
            field=models.CharField(choices=[('Leader', 'leader'), ('Team Member', 'team member'), ('Contributor', 'contributor')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='type',
            field=models.CharField(choices=[('Scoping', 'scoping'), ('Update', 'update'), ('Presentation', 'presentation'), ('Debrief', 'debrief')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Note', 'notes'), ('Minutes', 'minutes'), ('Scoping', 'scoping')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='Attachment 2021-03-19 20:39:09', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting 2021-03-19 20:39:09', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note 2021-03-19 20:39:09', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Requested', 'requested'), ('Scoping', 'scoping'), ('In Progress', 'in progress'), ('Complete', 'complete')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project 2021-03-19 20:39:09', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='type',
            field=models.CharField(choices=[('User', 'user'), ('Governance', 'governance'), ('Influencer', 'influencer'), ('Provider', 'provider'), ('Participant', 'participant')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Requirement', 'requirement'), ('Nice to Have', 'nice to have'), ('Blocker', 'blocker')], max_length=100, verbose_name='Type'),
        ),
    ]
