# Generated by Django 3.1.7 on 2021-03-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210319_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='status',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('scoped', 'Scoped'), ('in progress', 'In Progress'), ('blocked', 'Blocked'), ('validating', 'Validating'), ('complete', 'Complete')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='title',
            field=models.CharField(default='Action Item 2021-03-19 20:42:35', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='type',
            field=models.CharField(choices=[('leader', 'Leader'), ('team member', 'Team Member'), ('contributor', 'Contributor')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='type',
            field=models.CharField(choices=[('scoping', 'Scoping'), ('update', 'Update'), ('presentation', 'Presentation'), ('debrief', 'Debrief')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('notes', 'Note'), ('minutes', 'Minutes'), ('scoping', 'Scoping')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='Attachment 2021-03-19 20:42:35', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting 2021-03-19 20:42:35', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note 2021-03-19 20:42:35', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('scoping', 'Scoping'), ('in progress', 'In Progress'), ('complete', 'Complete')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project 2021-03-19 20:42:35', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='type',
            field=models.CharField(choices=[('user', 'User'), ('governance', 'Governance'), ('influencer', 'Influencer'), ('provider', 'Provider')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('requirement', 'Requirement'), ('nice to have', 'Nice to Have'), ('blocker', 'Blocker')], max_length=100, verbose_name='Type'),
        ),
    ]
