# Generated by Django 3.1.7 on 2021-03-19 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_auto_20210319_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='title',
            field=models.CharField(default='Action Item 2021-03-19 21:07:32', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='Attachment 2021-03-19 21:07:32', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting 2021-03-19 21:07:32', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note 2021-03-19 21:07:32', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project 2021-03-19 21:07:32', max_length=100, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='CommentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', djrichtextfield.models.RichTextField(verbose_name='Text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_to_action_item', to='app.actionitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
