# Generated by Django 3.1.7 on 2021-03-19 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_auto_20210319_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentItem',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='title',
            field=models.CharField(default='Action Item 2021-03-19 21:08:11', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='Attachment 2021-03-19 21:08:11', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting 2021-03-19 21:08:11', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note 2021-03-19 21:08:11', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project 2021-03-19 21:08:11', max_length=100, verbose_name='Title'),
        ),
    ]
